#!/bin/bash

# IPSec-IKEv2-Server - A Dockerised IKEv2/IPSec VPN server with L2TP support.
# Copyright (C) 2026  Tony HAU
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#6th command is supplied via ipparam in pppd config file (i.e. options.default_l2tp.client)
pppd_remote_gateway=$5
pppd_interface_name=$1
L2TP_SERVER_ADDR=$6

# Restore the original default route
restore_default_line=$(head -n 1 /tmp/l2tp-route-info | awk '{$1=$1};1')
ip route del default via $pppd_remote_gateway dev $pppd_interface_name
eval $restore_default_line

# Now delete the specific route to the L2TP server
current_default_interface=$(ip route show default | awk '/default/ {print $5}')
current_default_gateway=$(ip route show default | awk '/default/ {print $3}')

# Variables sanity check
printf "$$current_default_interface \n $current_default_gateway \n $pppd_remote_gateway \n $pppd_interface_name \n <NETWORK_INTERFACE_TO_BE_FORWARDED>" > /tmp/l2tp-client-ip-down-vars-info

# Disable IP forwarding
# Allow IP forwarding of packets that are not locally generated
sysctl -w net.ipv4.ip_forward=0 2>/dev/null

# Restore iptables forwarding rules
iptables -D FORWARD -i <NETWORK_INTERFACE_TO_BE_FORWARDED> -o $pppd_interface_name -j ACCEPT
iptables -D FORWARD -i <NETWORK_INTERFACE_TO_BE_FORWARDED> -o $pppd_interface_name -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -t nat -D POSTROUTING -o $pppd_interface_name -j MASQUERADE