# IPSec-IKEv2-Server - A Dockerised IKEv2/IPSec VPN server with L2TP support.
# Copyright (C) 2026  Tony HAU
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[global]
port = 1701
debug avp = yes
debug network = yes
debug packet = yes
debug state = yes
debug tunnel = yes                                                              
[lac client-l2tp]                                                 
lns = <L2TP_SERVER_ADDR>                                         
length bit = yes                                              
require chap = yes                                     
refuse pap = yes                                               
require authentication = yes 
redial = yes                
ppp debug = yes                                        
pppoptfile = /etc/ppp/options.default_l2tp.client 